  # Encoding: utf-8
  #
  # This is auto-generated code, changes will be overwritten.
  #
  # Copyright:: Copyright , Google Inc. All Rights Reserved.
  # License:: Licensed under the Apache License, Version 2.0.
  #
  # Code generated by AdsCommon library 0.9.9 on 2022-05-11 07:18:08.
  require 'ads_common/savon_service'
  require 'bing_ads_api/v13/ad_insight_service_registry'

  module BingAdsApi; module V13; module AdInsightService
  class AdInsightService < AdsCommonForBingAds::SavonService
    def initialize(config, endpoint)
		  namespace = 'https://bingads.microsoft.com/AdInsight/v13'
		  super(config, endpoint, namespace, :v13)
    end

    def get_bid_opportunities(*args, &block)
		  return execute_action('get_bid_opportunities', args, &block)
    end

    def get_budget_opportunities(*args, &block)
		  return execute_action('get_budget_opportunities', args, &block)
    end

    def get_keyword_opportunities(*args, &block)
		  return execute_action('get_keyword_opportunities', args, &block)
    end

    def get_estimated_bid_by_keyword_ids(*args, &block)
		  return execute_action('get_estimated_bid_by_keyword_ids', args, &block)
    end

    def get_estimated_position_by_keyword_ids(*args, &block)
		  return execute_action('get_estimated_position_by_keyword_ids', args, &block)
    end

    def get_estimated_bid_by_keywords(*args, &block)
		  return execute_action('get_estimated_bid_by_keywords', args, &block)
    end

    def get_estimated_position_by_keywords(*args, &block)
		  return execute_action('get_estimated_position_by_keywords', args, &block)
    end

    def get_bid_landscape_by_ad_group_ids(*args, &block)
		  return execute_action('get_bid_landscape_by_ad_group_ids', args, &block)
    end

    def get_bid_landscape_by_keyword_ids(*args, &block)
		  return execute_action('get_bid_landscape_by_keyword_ids', args, &block)
    end

    def get_historical_keyword_performance(*args, &block)
		  return execute_action('get_historical_keyword_performance', args, &block)
    end

    def get_historical_search_count(*args, &block)
		  return execute_action('get_historical_search_count', args, &block)
    end

    def get_keyword_categories(*args, &block)
		  return execute_action('get_keyword_categories', args, &block)
    end

    def get_keyword_demographics(*args, &block)
		  return execute_action('get_keyword_demographics', args, &block)
    end

    def get_keyword_locations(*args, &block)
		  return execute_action('get_keyword_locations', args, &block)
    end

    def suggest_keywords_for_url(*args, &block)
		  return execute_action('suggest_keywords_for_url', args, &block)
    end

    def suggest_keywords_from_existing_keywords(*args, &block)
		  return execute_action('suggest_keywords_from_existing_keywords', args, &block)
    end

    def get_auction_insight_data(*args, &block)
		  return execute_action('get_auction_insight_data', args, &block)
    end

    def get_domain_categories(*args, &block)
		  return execute_action('get_domain_categories', args, &block)
    end

    def put_metric_data(*args, &block)
		  return execute_action('put_metric_data', args, &block)
    end

    def get_keyword_idea_categories(*args, &block)
		  return execute_action('get_keyword_idea_categories', args, &block)
    end

    def get_keyword_ideas(*args, &block)
		  return execute_action('get_keyword_ideas', args, &block)
    end

    def get_keyword_traffic_estimates(*args, &block)
		  return execute_action('get_keyword_traffic_estimates', args, &block)
    end

    private

    def get_service_registry()
		  return AdInsightServiceRegistry
    end

    def get_module()
		  return BingAdsApi::V13::AdInsightService
    end
  end
  end; end; end