  # Encoding: utf-8
  #
  # This is auto-generated code, changes will be overwritten.
  #
  # Copyright:: Copyright 2022, Google Inc. All Rights Reserved.
  # License:: Licensed under the Apache License, Version 2.0.
  #
  # Code generated by AdsCommon library 1.0.3 on 2022-05-12 03:03:13.
  require 'ads_common/savon_service'
  require 'bing_ads_api/v13/bulk_service_registry'

  module BingAdsApi; module V13; module BulkService
  class BulkService < AdsCommonForBingAds::SavonService
    def initialize(config, endpoint)
		  namespace = 'https://bingads.microsoft.com/CampaignManagement/v13'
		  super(config, endpoint, namespace, :v13)
    end

    def download_campaigns_by_account_ids(*args, &block)
		  return execute_action('download_campaigns_by_account_ids', args, &block)
    end

    def download_campaigns_by_campaign_ids(*args, &block)
		  return execute_action('download_campaigns_by_campaign_ids', args, &block)
    end

    def get_bulk_download_status(*args, &block)
		  return execute_action('get_bulk_download_status', args, &block)
    end

    def get_bulk_upload_url(*args, &block)
		  return execute_action('get_bulk_upload_url', args, &block)
    end

    def get_bulk_upload_status(*args, &block)
		  return execute_action('get_bulk_upload_status', args, &block)
    end

    def upload_entity_records(*args, &block)
		  return execute_action('upload_entity_records', args, &block)
    end

    private

    def get_service_registry()
		  return BulkServiceRegistry
    end

    def get_module()
		  return BingAdsApi::V13::BulkService
    end
  end
  end; end; end