  # Encoding: utf-8
  #
  # This is auto-generated code, changes will be overwritten.
  #
  # Copyright:: Copyright , Google Inc. All Rights Reserved.
  # License:: Licensed under the Apache License, Version 2.0.
  #
  # Code generated by AdsCommon library 0.9.9 on 2022-05-11 07:19:05.
  require 'ads_common/savon_service'
  require 'bing_ads_api/v13/reporting_service_registry'

  module BingAdsApi; module V13; module ReportingService
  class ReportingService < AdsCommonForBingAds::SavonService
    def initialize(config, endpoint)
		  namespace = 'https://bingads.microsoft.com/Reporting/v13'
		  super(config, endpoint, namespace, :v13)
    end

    def submit_generate_report(*args, &block)
		  return execute_action('submit_generate_report', args, &block)
    end

    def poll_generate_report(*args, &block)
		  return execute_action('poll_generate_report', args, &block)
    end

    private

    def get_service_registry()
		  return ReportingServiceRegistry
    end

    def get_module()
		  return BingAdsApi::V13::ReportingService
    end
  end
  end; end; end